backend:
  name: git-gateway
  branch: main

media_folder: "images/blog"
public_folder: "/images/blog"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Etiqueta", name: "tag", widget: "string" }
      - { label: "Imagen de portada", name: "image", widget: "image" }
      - { label: "Resumen", name: "excerpt", widget: "text" }
      - { label: "Contenido", name: "body", widget: "markdown" }
